# Generated by Django 2.1.7 on 2019-03-18 15:34

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_game_time', models.CharField(default='00:00:00', max_length=10, verbose_name='total time')),
                ('pause', models.BooleanField(default=True, verbose_name='pause')),
                ('turn_run', models.BooleanField(default=False, verbose_name='turn run')),
                ('active', colorfield.fields.ColorField(max_length=18, verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(max_length=18, verbose_name='color')),
                ('total_player_time', models.CharField(default='00:00', max_length=10, verbose_name='player time')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_clock.Games', verbose_name='game')),
            ],
        ),
        migrations.CreateModel(
            name='Turns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(verbose_name='round')),
                ('turn_time', models.CharField(max_length=10, verbose_name='turn time')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_clock.Players', verbose_name='player')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=300, verbose_name='user id')),
                ('full_url', models.CharField(default='full_url', max_length=100, verbose_name='url')),
                ('short_url', models.CharField(default='short_url', max_length=50, verbose_name='short url')),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess_clock.Users', verbose_name='user'),
        ),
    ]
